export const WEATHER_IS_LOADING = 'WEATHER_IS_LOADING';
export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const SET_COMING_WEATHER = 'SET_COMING_WEATHER';
export const WEATHER_FETCH_DATA_FAIL = 'WEATHER_FETCH_DATA_FAIL';
export const CLEAR_CURRENT_WEATHER = 'CLEAR_CURRENT_WEATHER';
